experiments:
  experiment_dir: /Users/vsevolodparamonov/NeuralOptimalTransport/experiments
  exp_name: default

data:
  source_images: /Users/vsevolodparamonov/Downloads/img_align_celeba
  target_images: /Users/vsevolodparamonov/Downloads/cropped

training:
  device: cpu
  num_epochs: 32
  sampling_epochs: 1
  batch_size: 64

checkpoint:

model_params:
  noise_variance: 0.01

unet:

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 0.05

sampling:
  source_path: /Users/vsevolodparamonov/NeuralOptimalTransport/inference/source
  target_path: /Users/vsevolodparamonov/NeuralOptimalTransport/inference/target
