experiments:
  experiment_dir: /Users/vsevolodparamonov/NeuralOptimalTransport/experiments
  exp_name: default

data:
  source_images: /Users/vsevolodparamonov/Downloads/img_align_celeba
  target_images: /Users/vsevolodparamonov/Downloads/cropped
  image_size: 128

training:
  device: cpu
  num_iters: 32
  sampling_iters: 2
  metrics_step: 0
  batch_size: 4

checkpoint:

model_params:
  critic_fit_iters: 5
  noise_variance: 0.1

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 0.05

sampling:
  source_path: /Users/vsevolodparamonov/NeuralOptimalTransport/inference/source
  target_path: /Users/vsevolodparamonov/NeuralOptimalTransport/inference/target
