experiments:
  experiment_dir: /kaggle/working/NeuralOptimalTransport/experiments
  exp_name: default

data:
  source_images: /kaggle/input/source/img_align_celeba
  target_images: /kaggle/input/simpson
  image_size: 128

training:
  device: cuda
  num_iters: 25000
  sampling_iters: 30
  metrics_step: 0
  batch_size: 64

checkpoint:

model_params:
  critic_fit_iters: 10
  noise_variance: 0.01

unet:

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 5e-9

sampling:
  source_path: /kaggle/working/NeuralOptimalTransport/inference/source
  target_path: /kaggle/working/NeuralOptimalTransport/inference/target